#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 105
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 6

enum {
  sym__newline = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  sym_heading_level = 4,
  anon_sym_LBRACE_LBRACK = 5,
  anon_sym_RBRACK_RBRACE = 6,
  sym_code_content = 7,
  anon_sym_LBRACEv = 8,
  anon_sym_v_RBRACE = 9,
  sym_verbatim_content = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_inline_code_content = 13,
  anon_sym_LBRACEb = 14,
  anon_sym_LBRACEi = 15,
  anon_sym_LBRACEe = 16,
  anon_sym_LBRACE_BANG = 17,
  anon_sym_LBRACE_LBRACE_BANG = 18,
  aux_sym_ref_id_token1 = 19,
  anon_sym_LBRACE_LBRACE_COLON = 20,
  sym_ul_bullet = 21,
  sym_ol_number = 22,
  anon_sym_LBRACEul = 23,
  anon_sym_LBRACEol = 24,
  anon_sym_LBRACE_DASH = 25,
  anon_sym_LBRACEmath = 26,
  anon_sym_LBRACEm = 27,
  sym_math_content = 28,
  sym_word = 29,
  sym_document = 30,
  sym__block = 31,
  sym_paragraph = 32,
  sym_heading = 33,
  sym_heading_content = 34,
  sym_code_block = 35,
  sym_verbatim_block = 36,
  sym_inline_code = 37,
  sym_bold = 38,
  sym_italic = 39,
  sym_emph = 40,
  sym_ref = 41,
  sym_ref_with_text = 42,
  sym_ref_id = 43,
  sym_link = 44,
  sym_link_url = 45,
  sym_ul_item = 46,
  sym_ol_item = 47,
  sym_tagged_ul = 48,
  sym_tagged_ol = 49,
  sym_list_item = 50,
  sym_math_block = 51,
  sym_math_inline = 52,
  sym__inline = 53,
  aux_sym_document_repeat1 = 54,
  aux_sym_paragraph_repeat1 = 55,
  aux_sym_tagged_ul_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_heading_level] = "heading_level",
  [anon_sym_LBRACE_LBRACK] = "{[",
  [anon_sym_RBRACK_RBRACE] = "]}",
  [sym_code_content] = "code_content",
  [anon_sym_LBRACEv] = "{v",
  [anon_sym_v_RBRACE] = "v}",
  [sym_verbatim_content] = "verbatim_content",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_inline_code_content] = "inline_code_content",
  [anon_sym_LBRACEb] = "{b",
  [anon_sym_LBRACEi] = "{i",
  [anon_sym_LBRACEe] = "{e",
  [anon_sym_LBRACE_BANG] = "{!",
  [anon_sym_LBRACE_LBRACE_BANG] = "{{!",
  [aux_sym_ref_id_token1] = "ref_id_token1",
  [anon_sym_LBRACE_LBRACE_COLON] = "{{:",
  [sym_ul_bullet] = "ul_bullet",
  [sym_ol_number] = "ol_number",
  [anon_sym_LBRACEul] = "{ul",
  [anon_sym_LBRACEol] = "{ol",
  [anon_sym_LBRACE_DASH] = "{-",
  [anon_sym_LBRACEmath] = "{math",
  [anon_sym_LBRACEm] = "{m",
  [sym_math_content] = "math_content",
  [sym_word] = "word",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_paragraph] = "paragraph",
  [sym_heading] = "heading",
  [sym_heading_content] = "heading_content",
  [sym_code_block] = "code_block",
  [sym_verbatim_block] = "verbatim_block",
  [sym_inline_code] = "inline_code",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_emph] = "emph",
  [sym_ref] = "ref",
  [sym_ref_with_text] = "ref_with_text",
  [sym_ref_id] = "ref_id",
  [sym_link] = "link",
  [sym_link_url] = "link_url",
  [sym_ul_item] = "ul_item",
  [sym_ol_item] = "ol_item",
  [sym_tagged_ul] = "tagged_ul",
  [sym_tagged_ol] = "tagged_ol",
  [sym_list_item] = "list_item",
  [sym_math_block] = "math_block",
  [sym_math_inline] = "math_inline",
  [sym__inline] = "_inline",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_tagged_ul_repeat1] = "tagged_ul_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_heading_level] = sym_heading_level,
  [anon_sym_LBRACE_LBRACK] = anon_sym_LBRACE_LBRACK,
  [anon_sym_RBRACK_RBRACE] = anon_sym_RBRACK_RBRACE,
  [sym_code_content] = sym_code_content,
  [anon_sym_LBRACEv] = anon_sym_LBRACEv,
  [anon_sym_v_RBRACE] = anon_sym_v_RBRACE,
  [sym_verbatim_content] = sym_verbatim_content,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_inline_code_content] = sym_inline_code_content,
  [anon_sym_LBRACEb] = anon_sym_LBRACEb,
  [anon_sym_LBRACEi] = anon_sym_LBRACEi,
  [anon_sym_LBRACEe] = anon_sym_LBRACEe,
  [anon_sym_LBRACE_BANG] = anon_sym_LBRACE_BANG,
  [anon_sym_LBRACE_LBRACE_BANG] = anon_sym_LBRACE_LBRACE_BANG,
  [aux_sym_ref_id_token1] = aux_sym_ref_id_token1,
  [anon_sym_LBRACE_LBRACE_COLON] = anon_sym_LBRACE_LBRACE_COLON,
  [sym_ul_bullet] = sym_ul_bullet,
  [sym_ol_number] = sym_ol_number,
  [anon_sym_LBRACEul] = anon_sym_LBRACEul,
  [anon_sym_LBRACEol] = anon_sym_LBRACEol,
  [anon_sym_LBRACE_DASH] = anon_sym_LBRACE_DASH,
  [anon_sym_LBRACEmath] = anon_sym_LBRACEmath,
  [anon_sym_LBRACEm] = anon_sym_LBRACEm,
  [sym_math_content] = sym_math_content,
  [sym_word] = sym_word,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_paragraph] = sym_paragraph,
  [sym_heading] = sym_heading,
  [sym_heading_content] = sym_heading_content,
  [sym_code_block] = sym_code_block,
  [sym_verbatim_block] = sym_verbatim_block,
  [sym_inline_code] = sym_inline_code,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_emph] = sym_emph,
  [sym_ref] = sym_ref,
  [sym_ref_with_text] = sym_ref_with_text,
  [sym_ref_id] = sym_ref_id,
  [sym_link] = sym_link,
  [sym_link_url] = sym_link_url,
  [sym_ul_item] = sym_ul_item,
  [sym_ol_item] = sym_ol_item,
  [sym_tagged_ul] = sym_tagged_ul,
  [sym_tagged_ol] = sym_tagged_ol,
  [sym_list_item] = sym_list_item,
  [sym_math_block] = sym_math_block,
  [sym_math_inline] = sym_math_inline,
  [sym__inline] = sym__inline,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_tagged_ul_repeat1] = aux_sym_tagged_ul_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_level] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_code_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_v_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_verbatim_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_inline_code_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_ref_id_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_ul_bullet] = {
    .visible = true,
    .named = true,
  },
  [sym_ol_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEul] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEol] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEmath] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEm] = {
    .visible = true,
    .named = false,
  },
  [sym_math_content] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_content] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_block] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_code] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_emph] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_with_text] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_id] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_link_url] = {
    .visible = true,
    .named = true,
  },
  [sym_ul_item] = {
    .visible = true,
    .named = true,
  },
  [sym_ol_item] = {
    .visible = true,
    .named = true,
  },
  [sym_tagged_ul] = {
    .visible = true,
    .named = true,
  },
  [sym_tagged_ol] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_math_block] = {
    .visible = true,
    .named = true,
  },
  [sym_math_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__inline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tagged_ul_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_content = 1,
  field_id = 2,
  field_level = 3,
  field_text = 4,
  field_url = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_id] = "id",
  [field_level] = "level",
  [field_text] = "text",
  [field_url] = "url",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_id, 1},
  [2] =
    {field_content, 2},
    {field_level, 1},
  [4] =
    {field_id, 1},
    {field_text, 3},
  [6] =
    {field_text, 3},
    {field_url, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 9,
  [15] = 12,
  [16] = 13,
  [17] = 17,
  [18] = 5,
  [19] = 11,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 23,
  [27] = 27,
  [28] = 24,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 27,
  [33] = 31,
  [34] = 25,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 40,
  [54] = 52,
  [55] = 37,
  [56] = 45,
  [57] = 35,
  [58] = 39,
  [59] = 38,
  [60] = 44,
  [61] = 46,
  [62] = 50,
  [63] = 51,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 64,
  [68] = 66,
  [69] = 69,
  [70] = 70,
  [71] = 70,
  [72] = 69,
  [73] = 73,
  [74] = 74,
  [75] = 73,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 74,
  [83] = 76,
  [84] = 84,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 89,
  [98] = 92,
  [99] = 99,
  [100] = 93,
  [101] = 87,
  [102] = 90,
  [103] = 103,
  [104] = 104,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == 'v') ADVANCE(12);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(45);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == 'b') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(43);
      if (lookahead == 'm') ADVANCE(55);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == '{') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(46);
      if (lookahead == ':') ADVANCE(48);
      END_STATE();
    case 6:
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(62);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(54);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == '}') ADVANCE(31);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 16:
      if (lookahead == '}') ADVANCE(58);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(17)
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == ']') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != 'v') ADVANCE(37);
      if (lookahead == '\r') ADVANCE(37);
      if (lookahead == 'v') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(59);
      if (lookahead == '[') ADVANCE(38);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(23)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '!') ADVANCE(45);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == 'b') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(43);
      if (lookahead == 'm') ADVANCE(56);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == 'v') ADVANCE(34);
      if (lookahead == '{') ADVANCE(5);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '!') ADVANCE(45);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == 'b') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(43);
      if (lookahead == 'm') ADVANCE(56);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == 'v') ADVANCE(34);
      if (lookahead == '{') ADVANCE(5);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_heading_level);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_code_content);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == ']') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_code_content);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == ']') ADVANCE(21);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACEv);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_v_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_verbatim_content);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != 'v') ADVANCE(37);
      if (lookahead == '\r') ADVANCE(37);
      if (lookahead == 'v') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_verbatim_content);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != 'v') ADVANCE(37);
      if (lookahead == '\r') ADVANCE(37);
      if (lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_inline_code_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_inline_code_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACEb);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACEi);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACEe);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE_BANG);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_BANG);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_ref_id_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_COLON);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ul_bullet);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ol_number);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACEul);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACEol);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACEmath);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACEm);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACEm);
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_math_content);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_math_content);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '{') ADVANCE(16);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '.') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 23},
  [36] = {.lex_state = 23},
  [37] = {.lex_state = 23},
  [38] = {.lex_state = 23},
  [39] = {.lex_state = 23},
  [40] = {.lex_state = 23},
  [41] = {.lex_state = 23},
  [42] = {.lex_state = 23},
  [43] = {.lex_state = 23},
  [44] = {.lex_state = 23},
  [45] = {.lex_state = 23},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 23},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 23},
  [50] = {.lex_state = 23},
  [51] = {.lex_state = 23},
  [52] = {.lex_state = 23},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 17},
  [74] = {.lex_state = 17},
  [75] = {.lex_state = 17},
  [76] = {.lex_state = 17},
  [77] = {.lex_state = 19},
  [78] = {.lex_state = 20},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 7},
  [82] = {.lex_state = 17},
  [83] = {.lex_state = 17},
  [84] = {.lex_state = 18},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 18},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 18},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 23},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_heading_level] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(1),
    [anon_sym_LBRACEv] = ACTIONS(1),
    [anon_sym_v_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACEb] = ACTIONS(1),
    [anon_sym_LBRACEi] = ACTIONS(1),
    [anon_sym_LBRACEe] = ACTIONS(1),
    [anon_sym_LBRACE_BANG] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(1),
    [sym_ul_bullet] = ACTIONS(1),
    [anon_sym_LBRACEul] = ACTIONS(1),
    [anon_sym_LBRACEol] = ACTIONS(1),
    [anon_sym_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_LBRACEmath] = ACTIONS(1),
    [anon_sym_LBRACEm] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(99),
    [sym__block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym_heading] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_verbatim_block] = STATE(3),
    [sym_inline_code] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_emph] = STATE(4),
    [sym_ref] = STATE(4),
    [sym_ref_with_text] = STATE(4),
    [sym_link] = STATE(4),
    [sym_ul_item] = STATE(3),
    [sym_ol_item] = STATE(3),
    [sym_tagged_ul] = STATE(4),
    [sym_tagged_ol] = STATE(4),
    [sym_math_block] = STATE(3),
    [sym_math_inline] = STATE(4),
    [sym__inline] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACEv] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACEb] = ACTIONS(15),
    [anon_sym_LBRACEi] = ACTIONS(17),
    [anon_sym_LBRACEe] = ACTIONS(19),
    [anon_sym_LBRACE_BANG] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(25),
    [sym_ul_bullet] = ACTIONS(27),
    [sym_ol_number] = ACTIONS(29),
    [anon_sym_LBRACEul] = ACTIONS(31),
    [anon_sym_LBRACEol] = ACTIONS(33),
    [anon_sym_LBRACEmath] = ACTIONS(35),
    [anon_sym_LBRACEm] = ACTIONS(37),
    [sym_word] = ACTIONS(39),
  },
  [2] = {
    [sym__block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym_heading] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_verbatim_block] = STATE(2),
    [sym_inline_code] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_emph] = STATE(4),
    [sym_ref] = STATE(4),
    [sym_ref_with_text] = STATE(4),
    [sym_link] = STATE(4),
    [sym_ul_item] = STATE(2),
    [sym_ol_item] = STATE(2),
    [sym_tagged_ul] = STATE(4),
    [sym_tagged_ol] = STATE(4),
    [sym_math_block] = STATE(2),
    [sym_math_inline] = STATE(4),
    [sym__inline] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym__newline] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(46),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(49),
    [anon_sym_LBRACEv] = ACTIONS(52),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_LBRACEb] = ACTIONS(58),
    [anon_sym_LBRACEi] = ACTIONS(61),
    [anon_sym_LBRACEe] = ACTIONS(64),
    [anon_sym_LBRACE_BANG] = ACTIONS(67),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(70),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(73),
    [sym_ul_bullet] = ACTIONS(76),
    [sym_ol_number] = ACTIONS(79),
    [anon_sym_LBRACEul] = ACTIONS(82),
    [anon_sym_LBRACEol] = ACTIONS(85),
    [anon_sym_LBRACEmath] = ACTIONS(88),
    [anon_sym_LBRACEm] = ACTIONS(91),
    [sym_word] = ACTIONS(94),
  },
  [3] = {
    [sym__block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym_heading] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_verbatim_block] = STATE(2),
    [sym_inline_code] = STATE(4),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [sym_emph] = STATE(4),
    [sym_ref] = STATE(4),
    [sym_ref_with_text] = STATE(4),
    [sym_link] = STATE(4),
    [sym_ul_item] = STATE(2),
    [sym_ol_item] = STATE(2),
    [sym_tagged_ul] = STATE(4),
    [sym_tagged_ol] = STATE(4),
    [sym_math_block] = STATE(2),
    [sym_math_inline] = STATE(4),
    [sym__inline] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym__newline] = ACTIONS(99),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACEv] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACEb] = ACTIONS(15),
    [anon_sym_LBRACEi] = ACTIONS(17),
    [anon_sym_LBRACEe] = ACTIONS(19),
    [anon_sym_LBRACE_BANG] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(25),
    [sym_ul_bullet] = ACTIONS(27),
    [sym_ol_number] = ACTIONS(29),
    [anon_sym_LBRACEul] = ACTIONS(31),
    [anon_sym_LBRACEol] = ACTIONS(33),
    [anon_sym_LBRACEmath] = ACTIONS(35),
    [anon_sym_LBRACEm] = ACTIONS(37),
    [sym_word] = ACTIONS(39),
  },
  [4] = {
    [sym_inline_code] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_emph] = STATE(5),
    [sym_ref] = STATE(5),
    [sym_ref_with_text] = STATE(5),
    [sym_link] = STATE(5),
    [sym_tagged_ul] = STATE(5),
    [sym_tagged_ol] = STATE(5),
    [sym_math_inline] = STATE(5),
    [sym__inline] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym__newline] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(101),
    [anon_sym_LBRACEv] = ACTIONS(101),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACEb] = ACTIONS(15),
    [anon_sym_LBRACEi] = ACTIONS(17),
    [anon_sym_LBRACEe] = ACTIONS(19),
    [anon_sym_LBRACE_BANG] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(25),
    [sym_ul_bullet] = ACTIONS(101),
    [sym_ol_number] = ACTIONS(101),
    [anon_sym_LBRACEul] = ACTIONS(31),
    [anon_sym_LBRACEol] = ACTIONS(33),
    [anon_sym_LBRACEmath] = ACTIONS(101),
    [anon_sym_LBRACEm] = ACTIONS(37),
    [sym_word] = ACTIONS(105),
  },
  [5] = {
    [sym_inline_code] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_emph] = STATE(5),
    [sym_ref] = STATE(5),
    [sym_ref_with_text] = STATE(5),
    [sym_link] = STATE(5),
    [sym_tagged_ul] = STATE(5),
    [sym_tagged_ol] = STATE(5),
    [sym_math_inline] = STATE(5),
    [sym__inline] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym__newline] = ACTIONS(107),
    [anon_sym_LBRACE] = ACTIONS(109),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(107),
    [anon_sym_LBRACEv] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_LBRACEb] = ACTIONS(114),
    [anon_sym_LBRACEi] = ACTIONS(117),
    [anon_sym_LBRACEe] = ACTIONS(120),
    [anon_sym_LBRACE_BANG] = ACTIONS(123),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(126),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(129),
    [sym_ul_bullet] = ACTIONS(107),
    [sym_ol_number] = ACTIONS(107),
    [anon_sym_LBRACEul] = ACTIONS(132),
    [anon_sym_LBRACEol] = ACTIONS(135),
    [anon_sym_LBRACEmath] = ACTIONS(107),
    [anon_sym_LBRACEm] = ACTIONS(138),
    [sym_word] = ACTIONS(141),
  },
  [6] = {
    [sym_inline_code] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_emph] = STATE(5),
    [sym_ref] = STATE(5),
    [sym_ref_with_text] = STATE(5),
    [sym_link] = STATE(5),
    [sym_tagged_ul] = STATE(5),
    [sym_tagged_ol] = STATE(5),
    [sym_math_inline] = STATE(5),
    [sym__inline] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(144),
    [sym__newline] = ACTIONS(144),
    [anon_sym_LBRACE] = ACTIONS(146),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(144),
    [anon_sym_LBRACEv] = ACTIONS(144),
    [anon_sym_LBRACK] = ACTIONS(148),
    [anon_sym_LBRACEb] = ACTIONS(151),
    [anon_sym_LBRACEi] = ACTIONS(154),
    [anon_sym_LBRACEe] = ACTIONS(157),
    [anon_sym_LBRACE_BANG] = ACTIONS(160),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(163),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(166),
    [sym_ul_bullet] = ACTIONS(144),
    [sym_ol_number] = ACTIONS(144),
    [anon_sym_LBRACEul] = ACTIONS(169),
    [anon_sym_LBRACEol] = ACTIONS(172),
    [anon_sym_LBRACEmath] = ACTIONS(144),
    [anon_sym_LBRACEm] = ACTIONS(175),
    [sym_word] = ACTIONS(178),
  },
  [7] = {
    [sym_inline_code] = STATE(5),
    [sym_bold] = STATE(5),
    [sym_italic] = STATE(5),
    [sym_emph] = STATE(5),
    [sym_ref] = STATE(5),
    [sym_ref_with_text] = STATE(5),
    [sym_link] = STATE(5),
    [sym_tagged_ul] = STATE(5),
    [sym_tagged_ol] = STATE(5),
    [sym_math_inline] = STATE(5),
    [sym__inline] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(181),
    [sym__newline] = ACTIONS(181),
    [anon_sym_LBRACE] = ACTIONS(183),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(181),
    [anon_sym_LBRACEv] = ACTIONS(181),
    [anon_sym_LBRACK] = ACTIONS(185),
    [anon_sym_LBRACEb] = ACTIONS(188),
    [anon_sym_LBRACEi] = ACTIONS(191),
    [anon_sym_LBRACEe] = ACTIONS(194),
    [anon_sym_LBRACE_BANG] = ACTIONS(197),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(200),
    [anon_sym_LBRACE_LBRACE_COLON] = ACTIONS(203),
    [sym_ul_bullet] = ACTIONS(181),
    [sym_ol_number] = ACTIONS(181),
    [anon_sym_LBRACEul] = ACTIONS(206),
    [anon_sym_LBRACEol] = ACTIONS(209),
    [anon_sym_LBRACEmath] = ACTIONS(181),
    [anon_sym_LBRACEm] = ACTIONS(212),
    [sym_word] = ACTIONS(215),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [51] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [102] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [153] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [204] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [255] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [306] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [357] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [408] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(256), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [459] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [510] = 13,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(260), 1,
      anon_sym_LBRACK,
    ACTIONS(263), 1,
      anon_sym_LBRACEb,
    ACTIONS(266), 1,
      anon_sym_LBRACEi,
    ACTIONS(269), 1,
      anon_sym_LBRACEe,
    ACTIONS(272), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(275), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(278), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(281), 1,
      anon_sym_LBRACEul,
    ACTIONS(284), 1,
      anon_sym_LBRACEol,
    ACTIONS(287), 1,
      anon_sym_LBRACEm,
    ACTIONS(290), 1,
      sym_word,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [561] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(293), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [612] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 1,
      sym_word,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [663] = 13,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(297), 1,
      sym_word,
    STATE(103), 1,
      sym_heading_content,
    STATE(17), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [714] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(299), 1,
      sym_word,
    STATE(20), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [762] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(301), 1,
      sym_word,
    STATE(12), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [810] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(303), 1,
      sym_word,
    STATE(11), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [858] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(305), 1,
      sym_word,
    STATE(14), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [906] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(307), 1,
      sym_word,
    STATE(15), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [954] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(309), 1,
      sym_word,
    STATE(8), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1002] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(311), 1,
      sym_word,
    STATE(19), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1050] = 12,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACEb,
    ACTIONS(17), 1,
      anon_sym_LBRACEi,
    ACTIONS(19), 1,
      anon_sym_LBRACEe,
    ACTIONS(21), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(23), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(25), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(31), 1,
      anon_sym_LBRACEul,
    ACTIONS(33), 1,
      anon_sym_LBRACEol,
    ACTIONS(313), 1,
      anon_sym_LBRACEm,
    ACTIONS(315), 1,
      sym_word,
    STATE(6), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1098] = 12,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACEb,
    ACTIONS(17), 1,
      anon_sym_LBRACEi,
    ACTIONS(19), 1,
      anon_sym_LBRACEe,
    ACTIONS(21), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(23), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(25), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(31), 1,
      anon_sym_LBRACEul,
    ACTIONS(33), 1,
      anon_sym_LBRACEol,
    ACTIONS(313), 1,
      anon_sym_LBRACEm,
    ACTIONS(317), 1,
      sym_word,
    STATE(7), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1146] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(319), 1,
      sym_word,
    STATE(16), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1194] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(321), 1,
      sym_word,
    STATE(10), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1242] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(323), 1,
      sym_word,
    STATE(13), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1290] = 12,
    ACTIONS(220), 1,
      anon_sym_LBRACK,
    ACTIONS(222), 1,
      anon_sym_LBRACEb,
    ACTIONS(224), 1,
      anon_sym_LBRACEi,
    ACTIONS(226), 1,
      anon_sym_LBRACEe,
    ACTIONS(228), 1,
      anon_sym_LBRACE_BANG,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(232), 1,
      anon_sym_LBRACE_LBRACE_COLON,
    ACTIONS(234), 1,
      anon_sym_LBRACEul,
    ACTIONS(236), 1,
      anon_sym_LBRACEol,
    ACTIONS(238), 1,
      anon_sym_LBRACEm,
    ACTIONS(325), 1,
      sym_word,
    STATE(9), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1338] = 2,
    ACTIONS(329), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(327), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1362] = 2,
    ACTIONS(333), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(331), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1386] = 2,
    ACTIONS(337), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(335), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1410] = 2,
    ACTIONS(341), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(339), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1434] = 2,
    ACTIONS(345), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(343), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1458] = 2,
    ACTIONS(349), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(347), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1482] = 2,
    ACTIONS(353), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(351), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1506] = 2,
    ACTIONS(357), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(355), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1530] = 2,
    ACTIONS(361), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(359), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1554] = 2,
    ACTIONS(365), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(363), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1578] = 2,
    ACTIONS(369), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(367), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1602] = 2,
    ACTIONS(373), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(371), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1626] = 2,
    ACTIONS(377), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(375), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1650] = 2,
    ACTIONS(381), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(379), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1674] = 2,
    ACTIONS(385), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(383), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1698] = 2,
    ACTIONS(389), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(387), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1722] = 2,
    ACTIONS(393), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(391), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1746] = 2,
    ACTIONS(397), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(395), 16,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1770] = 1,
    ACTIONS(347), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1785] = 1,
    ACTIONS(395), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1800] = 1,
    ACTIONS(335), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1815] = 1,
    ACTIONS(367), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1830] = 1,
    ACTIONS(327), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1845] = 1,
    ACTIONS(343), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1860] = 1,
    ACTIONS(339), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1875] = 1,
    ACTIONS(363), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1890] = 1,
    ACTIONS(371), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1905] = 1,
    ACTIONS(387), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1920] = 1,
    ACTIONS(391), 12,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACE_COLON,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1935] = 3,
    ACTIONS(399), 1,
      anon_sym_RBRACE,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    STATE(65), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [1946] = 3,
    ACTIONS(403), 1,
      anon_sym_RBRACE,
    ACTIONS(405), 1,
      anon_sym_LBRACE_DASH,
    STATE(65), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [1957] = 3,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(408), 1,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [1968] = 3,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(410), 1,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [1979] = 3,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(412), 1,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [1990] = 2,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    STATE(67), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [1998] = 2,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    STATE(68), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2006] = 2,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    STATE(66), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2014] = 2,
    ACTIONS(401), 1,
      anon_sym_LBRACE_DASH,
    STATE(64), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2022] = 2,
    ACTIONS(414), 1,
      aux_sym_ref_id_token1,
    STATE(90), 1,
      sym_link_url,
  [2029] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(86), 1,
      sym_ref_id,
  [2036] = 2,
    ACTIONS(414), 1,
      aux_sym_ref_id_token1,
    STATE(102), 1,
      sym_link_url,
  [2043] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(101), 1,
      sym_ref_id,
  [2050] = 2,
    ACTIONS(418), 1,
      anon_sym_RBRACK_RBRACE,
    ACTIONS(420), 1,
      sym_code_content,
  [2057] = 2,
    ACTIONS(422), 1,
      anon_sym_v_RBRACE,
    ACTIONS(424), 1,
      sym_verbatim_content,
  [2064] = 1,
    ACTIONS(426), 2,
      anon_sym_RBRACE,
      anon_sym_LBRACE_DASH,
  [2069] = 2,
    ACTIONS(428), 1,
      anon_sym_RBRACK,
    ACTIONS(430), 1,
      sym_inline_code_content,
  [2076] = 2,
    ACTIONS(432), 1,
      anon_sym_RBRACK,
    ACTIONS(434), 1,
      sym_inline_code_content,
  [2083] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(85), 1,
      sym_ref_id,
  [2090] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(87), 1,
      sym_ref_id,
  [2097] = 2,
    ACTIONS(436), 1,
      anon_sym_RBRACE,
    ACTIONS(438), 1,
      sym_math_content,
  [2104] = 1,
    ACTIONS(440), 1,
      anon_sym_RBRACE,
  [2108] = 1,
    ACTIONS(442), 1,
      anon_sym_RBRACE,
  [2112] = 1,
    ACTIONS(444), 1,
      anon_sym_RBRACE,
  [2116] = 1,
    ACTIONS(446), 1,
      anon_sym_RBRACE,
  [2120] = 1,
    ACTIONS(448), 1,
      anon_sym_RBRACE,
  [2124] = 1,
    ACTIONS(450), 1,
      anon_sym_RBRACE,
  [2128] = 1,
    ACTIONS(452), 1,
      sym_heading_level,
  [2132] = 1,
    ACTIONS(454), 1,
      sym_math_content,
  [2136] = 1,
    ACTIONS(456), 1,
      anon_sym_RBRACK,
  [2140] = 1,
    ACTIONS(458), 1,
      anon_sym_RBRACE,
  [2144] = 1,
    ACTIONS(460), 1,
      anon_sym_v_RBRACE,
  [2148] = 1,
    ACTIONS(462), 1,
      anon_sym_RBRACE,
  [2152] = 1,
    ACTIONS(464), 1,
      anon_sym_RBRACE,
  [2156] = 1,
    ACTIONS(466), 1,
      sym_math_content,
  [2160] = 1,
    ACTIONS(468), 1,
      ts_builtin_sym_end,
  [2164] = 1,
    ACTIONS(470), 1,
      anon_sym_RBRACK,
  [2168] = 1,
    ACTIONS(472), 1,
      anon_sym_RBRACE,
  [2172] = 1,
    ACTIONS(474), 1,
      anon_sym_RBRACE,
  [2176] = 1,
    ACTIONS(476), 1,
      anon_sym_RBRACE,
  [2180] = 1,
    ACTIONS(478), 1,
      anon_sym_RBRACK_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 51,
  [SMALL_STATE(10)] = 102,
  [SMALL_STATE(11)] = 153,
  [SMALL_STATE(12)] = 204,
  [SMALL_STATE(13)] = 255,
  [SMALL_STATE(14)] = 306,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 408,
  [SMALL_STATE(17)] = 459,
  [SMALL_STATE(18)] = 510,
  [SMALL_STATE(19)] = 561,
  [SMALL_STATE(20)] = 612,
  [SMALL_STATE(21)] = 663,
  [SMALL_STATE(22)] = 714,
  [SMALL_STATE(23)] = 762,
  [SMALL_STATE(24)] = 810,
  [SMALL_STATE(25)] = 858,
  [SMALL_STATE(26)] = 906,
  [SMALL_STATE(27)] = 954,
  [SMALL_STATE(28)] = 1002,
  [SMALL_STATE(29)] = 1050,
  [SMALL_STATE(30)] = 1098,
  [SMALL_STATE(31)] = 1146,
  [SMALL_STATE(32)] = 1194,
  [SMALL_STATE(33)] = 1242,
  [SMALL_STATE(34)] = 1290,
  [SMALL_STATE(35)] = 1338,
  [SMALL_STATE(36)] = 1362,
  [SMALL_STATE(37)] = 1386,
  [SMALL_STATE(38)] = 1410,
  [SMALL_STATE(39)] = 1434,
  [SMALL_STATE(40)] = 1458,
  [SMALL_STATE(41)] = 1482,
  [SMALL_STATE(42)] = 1506,
  [SMALL_STATE(43)] = 1530,
  [SMALL_STATE(44)] = 1554,
  [SMALL_STATE(45)] = 1578,
  [SMALL_STATE(46)] = 1602,
  [SMALL_STATE(47)] = 1626,
  [SMALL_STATE(48)] = 1650,
  [SMALL_STATE(49)] = 1674,
  [SMALL_STATE(50)] = 1698,
  [SMALL_STATE(51)] = 1722,
  [SMALL_STATE(52)] = 1746,
  [SMALL_STATE(53)] = 1770,
  [SMALL_STATE(54)] = 1785,
  [SMALL_STATE(55)] = 1800,
  [SMALL_STATE(56)] = 1815,
  [SMALL_STATE(57)] = 1830,
  [SMALL_STATE(58)] = 1845,
  [SMALL_STATE(59)] = 1860,
  [SMALL_STATE(60)] = 1875,
  [SMALL_STATE(61)] = 1890,
  [SMALL_STATE(62)] = 1905,
  [SMALL_STATE(63)] = 1920,
  [SMALL_STATE(64)] = 1935,
  [SMALL_STATE(65)] = 1946,
  [SMALL_STATE(66)] = 1957,
  [SMALL_STATE(67)] = 1968,
  [SMALL_STATE(68)] = 1979,
  [SMALL_STATE(69)] = 1990,
  [SMALL_STATE(70)] = 1998,
  [SMALL_STATE(71)] = 2006,
  [SMALL_STATE(72)] = 2014,
  [SMALL_STATE(73)] = 2022,
  [SMALL_STATE(74)] = 2029,
  [SMALL_STATE(75)] = 2036,
  [SMALL_STATE(76)] = 2043,
  [SMALL_STATE(77)] = 2050,
  [SMALL_STATE(78)] = 2057,
  [SMALL_STATE(79)] = 2064,
  [SMALL_STATE(80)] = 2069,
  [SMALL_STATE(81)] = 2076,
  [SMALL_STATE(82)] = 2083,
  [SMALL_STATE(83)] = 2090,
  [SMALL_STATE(84)] = 2097,
  [SMALL_STATE(85)] = 2104,
  [SMALL_STATE(86)] = 2108,
  [SMALL_STATE(87)] = 2112,
  [SMALL_STATE(88)] = 2116,
  [SMALL_STATE(89)] = 2120,
  [SMALL_STATE(90)] = 2124,
  [SMALL_STATE(91)] = 2128,
  [SMALL_STATE(92)] = 2132,
  [SMALL_STATE(93)] = 2136,
  [SMALL_STATE(94)] = 2140,
  [SMALL_STATE(95)] = 2144,
  [SMALL_STATE(96)] = 2148,
  [SMALL_STATE(97)] = 2152,
  [SMALL_STATE(98)] = 2156,
  [SMALL_STATE(99)] = 2160,
  [SMALL_STATE(100)] = 2164,
  [SMALL_STATE(101)] = 2168,
  [SMALL_STATE(102)] = 2172,
  [SMALL_STATE(103)] = 2176,
  [SMALL_STATE(104)] = 2180,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(91),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(77),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(78),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(80),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(33),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(23),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(34),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(82),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(83),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(73),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(30),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(71),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(72),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(84),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(92),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(80),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(33),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(23),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(34),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(82),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(83),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(73),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(71),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(72),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(92),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(5),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ol_item, 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ol_item, 2),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(80),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(33),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(23),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(34),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(82),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(83),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(73),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(71),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(72),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ol_item, 2), SHIFT(92),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ol_item, 2), SHIFT(5),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ul_item, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ul_item, 2),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(80),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(33),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(23),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(34),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(82),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(83),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(73),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(71),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(72),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ul_item, 2), SHIFT(92),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ul_item, 2), SHIFT(5),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_content, 1),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(81),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(31),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(26),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(25),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(74),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(76),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(75),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(70),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(69),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(98),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(18),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_ol, 3),
  [329] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tagged_ol, 3),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_block, 3, .production_id = 1),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_block, 3, .production_id = 1),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, .production_id = 5),
  [337] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, .production_id = 5),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emph, 3, .production_id = 1),
  [341] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emph, 3, .production_id = 1),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_ul, 3),
  [345] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tagged_ul, 3),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_inline, 3, .production_id = 1),
  [349] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_inline, 3, .production_id = 1),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_block, 2),
  [353] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_block, 2),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, .production_id = 3),
  [357] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4, .production_id = 3),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 2),
  [361] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 2),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_code, 2),
  [365] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_code, 2),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_with_text, 5, .production_id = 4),
  [369] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_with_text, 5, .production_id = 4),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 3, .production_id = 2),
  [373] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 3, .production_id = 2),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_block, 2),
  [377] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_block, 2),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, .production_id = 1),
  [381] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, .production_id = 1),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_block, 3, .production_id = 1),
  [385] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_block, 3, .production_id = 1),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_code, 3),
  [389] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_code, 3),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, .production_id = 1),
  [393] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, .production_id = 1),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, .production_id = 1),
  [397] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, .production_id = 1),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [403] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tagged_ul_repeat1, 2),
  [405] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tagged_ul_repeat1, 2), SHIFT_REPEAT(22),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [418] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [422] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [426] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3),
  [428] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [432] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [436] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [446] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_url, 1),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [452] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [456] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [458] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_id, 1),
  [460] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [462] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [464] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [466] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [468] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [470] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [472] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [474] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [476] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [478] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_odoc_mld(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
