#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 110
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 6

enum {
  sym__newline = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  sym_heading_level = 4,
  anon_sym_LBRACE_LBRACK = 5,
  anon_sym_RBRACK_RBRACE = 6,
  sym_code_content = 7,
  anon_sym_LBRACEv = 8,
  anon_sym_v_RBRACE = 9,
  sym_verbatim_content = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  sym_inline_code_content = 13,
  anon_sym_LBRACEb = 14,
  anon_sym_LBRACEi = 15,
  anon_sym_LBRACEe = 16,
  anon_sym_BANG = 17,
  aux_sym_ref_id_token1 = 18,
  anon_sym_COLON = 19,
  sym_ul_bullet = 20,
  sym_ol_number = 21,
  anon_sym_LBRACEul = 22,
  anon_sym_LBRACEol = 23,
  anon_sym_LBRACE_DASH = 24,
  anon_sym_LBRACEmath = 25,
  anon_sym_LBRACEm = 26,
  sym_math_content = 27,
  sym_word = 28,
  sym_document = 29,
  sym__block = 30,
  sym_paragraph = 31,
  sym_heading = 32,
  sym_heading_content = 33,
  sym_code_block = 34,
  sym_verbatim_block = 35,
  sym_inline_code = 36,
  sym_bold = 37,
  sym_italic = 38,
  sym_emph = 39,
  sym_ref = 40,
  sym_ref_with_text = 41,
  sym_ref_id = 42,
  sym_link = 43,
  sym_link_url = 44,
  sym_ul_item = 45,
  sym_ol_item = 46,
  sym_tagged_ul = 47,
  sym_tagged_ol = 48,
  sym_list_item = 49,
  sym_math_block = 50,
  sym_math_inline = 51,
  sym__inline = 52,
  aux_sym_document_repeat1 = 53,
  aux_sym_paragraph_repeat1 = 54,
  aux_sym_link_repeat1 = 55,
  aux_sym_tagged_ul_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_heading_level] = "heading_level",
  [anon_sym_LBRACE_LBRACK] = "{[",
  [anon_sym_RBRACK_RBRACE] = "]}",
  [sym_code_content] = "code_content",
  [anon_sym_LBRACEv] = "{v",
  [anon_sym_v_RBRACE] = "v}",
  [sym_verbatim_content] = "verbatim_content",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_inline_code_content] = "inline_code_content",
  [anon_sym_LBRACEb] = "{b",
  [anon_sym_LBRACEi] = "{i",
  [anon_sym_LBRACEe] = "{e",
  [anon_sym_BANG] = "!",
  [aux_sym_ref_id_token1] = "ref_id_token1",
  [anon_sym_COLON] = ":",
  [sym_ul_bullet] = "ul_bullet",
  [sym_ol_number] = "ol_number",
  [anon_sym_LBRACEul] = "{ul",
  [anon_sym_LBRACEol] = "{ol",
  [anon_sym_LBRACE_DASH] = "{-",
  [anon_sym_LBRACEmath] = "{math",
  [anon_sym_LBRACEm] = "{m",
  [sym_math_content] = "math_content",
  [sym_word] = "word",
  [sym_document] = "document",
  [sym__block] = "_block",
  [sym_paragraph] = "paragraph",
  [sym_heading] = "heading",
  [sym_heading_content] = "heading_content",
  [sym_code_block] = "code_block",
  [sym_verbatim_block] = "verbatim_block",
  [sym_inline_code] = "inline_code",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [sym_emph] = "emph",
  [sym_ref] = "ref",
  [sym_ref_with_text] = "ref_with_text",
  [sym_ref_id] = "ref_id",
  [sym_link] = "link",
  [sym_link_url] = "link_url",
  [sym_ul_item] = "ul_item",
  [sym_ol_item] = "ol_item",
  [sym_tagged_ul] = "tagged_ul",
  [sym_tagged_ol] = "tagged_ol",
  [sym_list_item] = "list_item",
  [sym_math_block] = "math_block",
  [sym_math_inline] = "math_inline",
  [sym__inline] = "_inline",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_link_repeat1] = "link_repeat1",
  [aux_sym_tagged_ul_repeat1] = "tagged_ul_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_heading_level] = sym_heading_level,
  [anon_sym_LBRACE_LBRACK] = anon_sym_LBRACE_LBRACK,
  [anon_sym_RBRACK_RBRACE] = anon_sym_RBRACK_RBRACE,
  [sym_code_content] = sym_code_content,
  [anon_sym_LBRACEv] = anon_sym_LBRACEv,
  [anon_sym_v_RBRACE] = anon_sym_v_RBRACE,
  [sym_verbatim_content] = sym_verbatim_content,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_inline_code_content] = sym_inline_code_content,
  [anon_sym_LBRACEb] = anon_sym_LBRACEb,
  [anon_sym_LBRACEi] = anon_sym_LBRACEi,
  [anon_sym_LBRACEe] = anon_sym_LBRACEe,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_ref_id_token1] = aux_sym_ref_id_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_ul_bullet] = sym_ul_bullet,
  [sym_ol_number] = sym_ol_number,
  [anon_sym_LBRACEul] = anon_sym_LBRACEul,
  [anon_sym_LBRACEol] = anon_sym_LBRACEol,
  [anon_sym_LBRACE_DASH] = anon_sym_LBRACE_DASH,
  [anon_sym_LBRACEmath] = anon_sym_LBRACEmath,
  [anon_sym_LBRACEm] = anon_sym_LBRACEm,
  [sym_math_content] = sym_math_content,
  [sym_word] = sym_word,
  [sym_document] = sym_document,
  [sym__block] = sym__block,
  [sym_paragraph] = sym_paragraph,
  [sym_heading] = sym_heading,
  [sym_heading_content] = sym_heading_content,
  [sym_code_block] = sym_code_block,
  [sym_verbatim_block] = sym_verbatim_block,
  [sym_inline_code] = sym_inline_code,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [sym_emph] = sym_emph,
  [sym_ref] = sym_ref,
  [sym_ref_with_text] = sym_ref_with_text,
  [sym_ref_id] = sym_ref_id,
  [sym_link] = sym_link,
  [sym_link_url] = sym_link_url,
  [sym_ul_item] = sym_ul_item,
  [sym_ol_item] = sym_ol_item,
  [sym_tagged_ul] = sym_tagged_ul,
  [sym_tagged_ol] = sym_tagged_ol,
  [sym_list_item] = sym_list_item,
  [sym_math_block] = sym_math_block,
  [sym_math_inline] = sym_math_inline,
  [sym__inline] = sym__inline,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_link_repeat1] = aux_sym_link_repeat1,
  [aux_sym_tagged_ul_repeat1] = aux_sym_tagged_ul_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_level] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_code_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_v_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_verbatim_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_inline_code_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_ref_id_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_ul_bullet] = {
    .visible = true,
    .named = true,
  },
  [sym_ol_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEul] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEol] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEmath] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEm] = {
    .visible = true,
    .named = false,
  },
  [sym_math_content] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_content] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_block] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_code] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_emph] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_with_text] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_id] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_link_url] = {
    .visible = true,
    .named = true,
  },
  [sym_ul_item] = {
    .visible = true,
    .named = true,
  },
  [sym_ol_item] = {
    .visible = true,
    .named = true,
  },
  [sym_tagged_ul] = {
    .visible = true,
    .named = true,
  },
  [sym_tagged_ol] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_math_block] = {
    .visible = true,
    .named = true,
  },
  [sym_math_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__inline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tagged_ul_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_content = 1,
  field_id = 2,
  field_level = 3,
  field_text = 4,
  field_url = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_id] = "id",
  [field_level] = "level",
  [field_text] = "text",
  [field_url] = "url",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_content, 2},
    {field_level, 1},
  [3] =
    {field_id, 2},
  [4] =
    {field_id, 3},
    {field_text, 5},
  [6] =
    {field_text, 5},
    {field_url, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 17,
  [18] = 18,
  [19] = 12,
  [20] = 20,
  [21] = 18,
  [22] = 4,
  [23] = 17,
  [24] = 15,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 29,
  [30] = 26,
  [31] = 31,
  [32] = 29,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 41,
  [55] = 44,
  [56] = 39,
  [57] = 38,
  [58] = 43,
  [59] = 46,
  [60] = 37,
  [61] = 52,
  [62] = 51,
  [63] = 50,
  [64] = 49,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 65,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 71,
  [74] = 70,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 83,
  [85] = 82,
  [86] = 80,
  [87] = 78,
  [88] = 76,
  [89] = 79,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 92,
  [99] = 99,
  [100] = 93,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 102,
  [106] = 104,
  [107] = 95,
  [108] = 108,
  [109] = 97,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '!') ADVANCE(48);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == 'v') ADVANCE(13);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(64);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(60);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(48);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '4')) ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(55);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(56);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '{') ADVANCE(6);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12)
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(38);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(38);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 15:
      if (lookahead == '}') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == '}') ADVANCE(34);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == '}') ADVANCE(60);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(18)
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}') ADVANCE(49);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(36);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != 'v') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(40);
      if (lookahead == 'v') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(40);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(15);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(24)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '-') ADVANCE(55);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == 'b') ADVANCE(45);
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'm') ADVANCE(58);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == 'v') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == 'b') ADVANCE(45);
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'm') ADVANCE(58);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead == 'v') ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == 'b') ADVANCE(45);
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'm') ADVANCE(57);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_heading_level);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_code_content);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(36);
      if (lookahead == ']') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_code_content);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(36);
      if (lookahead == ']') ADVANCE(23);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACEv);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_v_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_verbatim_content);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != 'v') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(40);
      if (lookahead == 'v') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_verbatim_content);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != 'v') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(40);
      if (lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_inline_code_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_inline_code_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACEb);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACEi);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACEe);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_ref_id_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '}') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ul_bullet);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ol_number);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACEul);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACEol);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACE_DASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACEmath);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LBRACEm);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACEm);
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_math_content);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_math_content);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '{') ADVANCE(17);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '.') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(64);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 24},
  [37] = {.lex_state = 24},
  [38] = {.lex_state = 24},
  [39] = {.lex_state = 24},
  [40] = {.lex_state = 24},
  [41] = {.lex_state = 24},
  [42] = {.lex_state = 24},
  [43] = {.lex_state = 24},
  [44] = {.lex_state = 24},
  [45] = {.lex_state = 24},
  [46] = {.lex_state = 24},
  [47] = {.lex_state = 24},
  [48] = {.lex_state = 24},
  [49] = {.lex_state = 24},
  [50] = {.lex_state = 24},
  [51] = {.lex_state = 24},
  [52] = {.lex_state = 24},
  [53] = {.lex_state = 24},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 12},
  [69] = {.lex_state = 12},
  [70] = {.lex_state = 12},
  [71] = {.lex_state = 12},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 12},
  [74] = {.lex_state = 12},
  [75] = {.lex_state = 21},
  [76] = {.lex_state = 18},
  [77] = {.lex_state = 20},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 5},
  [80] = {.lex_state = 18},
  [81] = {.lex_state = 12},
  [82] = {.lex_state = 18},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 18},
  [86] = {.lex_state = 18},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 18},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 19},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 19},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 19},
  [101] = {.lex_state = 24},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_heading_level] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(1),
    [anon_sym_LBRACEv] = ACTIONS(1),
    [anon_sym_v_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACEb] = ACTIONS(1),
    [anon_sym_LBRACEi] = ACTIONS(1),
    [anon_sym_LBRACEe] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_ul_bullet] = ACTIONS(1),
    [anon_sym_LBRACEul] = ACTIONS(1),
    [anon_sym_LBRACEol] = ACTIONS(1),
    [anon_sym_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_LBRACEmath] = ACTIONS(1),
    [anon_sym_LBRACEm] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(94),
    [sym__block] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym_heading] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_verbatim_block] = STATE(3),
    [sym_inline_code] = STATE(7),
    [sym_bold] = STATE(7),
    [sym_italic] = STATE(7),
    [sym_emph] = STATE(7),
    [sym_ref] = STATE(7),
    [sym_ref_with_text] = STATE(7),
    [sym_link] = STATE(7),
    [sym_ul_item] = STATE(3),
    [sym_ol_item] = STATE(3),
    [sym_tagged_ul] = STATE(7),
    [sym_tagged_ol] = STATE(7),
    [sym_math_block] = STATE(3),
    [sym_math_inline] = STATE(7),
    [sym__inline] = STATE(7),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACEv] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACEb] = ACTIONS(15),
    [anon_sym_LBRACEi] = ACTIONS(17),
    [anon_sym_LBRACEe] = ACTIONS(19),
    [sym_ul_bullet] = ACTIONS(21),
    [sym_ol_number] = ACTIONS(23),
    [anon_sym_LBRACEul] = ACTIONS(25),
    [anon_sym_LBRACEol] = ACTIONS(27),
    [anon_sym_LBRACEmath] = ACTIONS(29),
    [anon_sym_LBRACEm] = ACTIONS(31),
    [sym_word] = ACTIONS(33),
  },
  [2] = {
    [sym__block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym_heading] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_verbatim_block] = STATE(2),
    [sym_inline_code] = STATE(7),
    [sym_bold] = STATE(7),
    [sym_italic] = STATE(7),
    [sym_emph] = STATE(7),
    [sym_ref] = STATE(7),
    [sym_ref_with_text] = STATE(7),
    [sym_link] = STATE(7),
    [sym_ul_item] = STATE(2),
    [sym_ol_item] = STATE(2),
    [sym_tagged_ul] = STATE(7),
    [sym_tagged_ol] = STATE(7),
    [sym_math_block] = STATE(2),
    [sym_math_inline] = STATE(7),
    [sym__inline] = STATE(7),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym__newline] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(40),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(43),
    [anon_sym_LBRACEv] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(49),
    [anon_sym_LBRACEb] = ACTIONS(52),
    [anon_sym_LBRACEi] = ACTIONS(55),
    [anon_sym_LBRACEe] = ACTIONS(58),
    [sym_ul_bullet] = ACTIONS(61),
    [sym_ol_number] = ACTIONS(64),
    [anon_sym_LBRACEul] = ACTIONS(67),
    [anon_sym_LBRACEol] = ACTIONS(70),
    [anon_sym_LBRACEmath] = ACTIONS(73),
    [anon_sym_LBRACEm] = ACTIONS(76),
    [sym_word] = ACTIONS(79),
  },
  [3] = {
    [sym__block] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym_heading] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_verbatim_block] = STATE(2),
    [sym_inline_code] = STATE(7),
    [sym_bold] = STATE(7),
    [sym_italic] = STATE(7),
    [sym_emph] = STATE(7),
    [sym_ref] = STATE(7),
    [sym_ref_with_text] = STATE(7),
    [sym_link] = STATE(7),
    [sym_ul_item] = STATE(2),
    [sym_ol_item] = STATE(2),
    [sym_tagged_ul] = STATE(7),
    [sym_tagged_ol] = STATE(7),
    [sym_math_block] = STATE(2),
    [sym_math_inline] = STATE(7),
    [sym__inline] = STATE(7),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(82),
    [sym__newline] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACEv] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACEb] = ACTIONS(15),
    [anon_sym_LBRACEi] = ACTIONS(17),
    [anon_sym_LBRACEe] = ACTIONS(19),
    [sym_ul_bullet] = ACTIONS(21),
    [sym_ol_number] = ACTIONS(23),
    [anon_sym_LBRACEul] = ACTIONS(25),
    [anon_sym_LBRACEol] = ACTIONS(27),
    [anon_sym_LBRACEmath] = ACTIONS(29),
    [anon_sym_LBRACEm] = ACTIONS(31),
    [sym_word] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      anon_sym_LBRACEb,
    ACTIONS(97), 1,
      anon_sym_LBRACEi,
    ACTIONS(100), 1,
      anon_sym_LBRACEe,
    ACTIONS(103), 1,
      anon_sym_LBRACEul,
    ACTIONS(106), 1,
      anon_sym_LBRACEol,
    ACTIONS(109), 1,
      anon_sym_LBRACEm,
    ACTIONS(112), 1,
      sym_word,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEmath,
    STATE(4), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [51] = 11,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    ACTIONS(120), 1,
      anon_sym_LBRACK,
    ACTIONS(123), 1,
      anon_sym_LBRACEb,
    ACTIONS(126), 1,
      anon_sym_LBRACEi,
    ACTIONS(129), 1,
      anon_sym_LBRACEe,
    ACTIONS(132), 1,
      anon_sym_LBRACEul,
    ACTIONS(135), 1,
      anon_sym_LBRACEol,
    ACTIONS(138), 1,
      anon_sym_LBRACEm,
    ACTIONS(141), 1,
      sym_word,
    ACTIONS(115), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEmath,
    STATE(4), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [102] = 11,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      anon_sym_LBRACK,
    ACTIONS(152), 1,
      anon_sym_LBRACEb,
    ACTIONS(155), 1,
      anon_sym_LBRACEi,
    ACTIONS(158), 1,
      anon_sym_LBRACEe,
    ACTIONS(161), 1,
      anon_sym_LBRACEul,
    ACTIONS(164), 1,
      anon_sym_LBRACEol,
    ACTIONS(167), 1,
      anon_sym_LBRACEm,
    ACTIONS(170), 1,
      sym_word,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEmath,
    STATE(4), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [153] = 11,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACEb,
    ACTIONS(17), 1,
      anon_sym_LBRACEi,
    ACTIONS(19), 1,
      anon_sym_LBRACEe,
    ACTIONS(25), 1,
      anon_sym_LBRACEul,
    ACTIONS(27), 1,
      anon_sym_LBRACEol,
    ACTIONS(31), 1,
      anon_sym_LBRACEm,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 1,
      sym_word,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEmath,
    STATE(4), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [204] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(179), 2,
      sym__newline,
      sym_word,
    STATE(9), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_link_repeat1,
  [250] = 11,
    ACTIONS(202), 1,
      anon_sym_LBRACE,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    ACTIONS(207), 1,
      anon_sym_LBRACK,
    ACTIONS(210), 1,
      anon_sym_LBRACEb,
    ACTIONS(213), 1,
      anon_sym_LBRACEi,
    ACTIONS(216), 1,
      anon_sym_LBRACEe,
    ACTIONS(219), 1,
      anon_sym_LBRACEul,
    ACTIONS(222), 1,
      anon_sym_LBRACEol,
    ACTIONS(225), 1,
      anon_sym_LBRACEm,
    ACTIONS(199), 2,
      sym__newline,
      sym_word,
    STATE(9), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_link_repeat1,
  [296] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    ACTIONS(179), 2,
      sym__newline,
      sym_word,
    STATE(9), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_link_repeat1,
  [342] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    ACTIONS(232), 1,
      sym_word,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [387] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [432] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [477] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [522] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(240), 2,
      sym__newline,
      sym_word,
    STATE(8), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_link_repeat1,
  [565] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [610] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [655] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [700] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [745] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(250), 1,
      sym_word,
    STATE(91), 1,
      sym_heading_content,
    STATE(14), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [790] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [835] = 11,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    ACTIONS(257), 1,
      anon_sym_LBRACK,
    ACTIONS(260), 1,
      anon_sym_LBRACEb,
    ACTIONS(263), 1,
      anon_sym_LBRACEi,
    ACTIONS(266), 1,
      anon_sym_LBRACEe,
    ACTIONS(269), 1,
      anon_sym_LBRACEul,
    ACTIONS(272), 1,
      anon_sym_LBRACEol,
    ACTIONS(275), 1,
      anon_sym_LBRACEm,
    ACTIONS(278), 1,
      sym_word,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [880] = 11,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(232), 1,
      sym_word,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
    STATE(22), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [925] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(283), 2,
      sym__newline,
      sym_word,
    STATE(10), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_link_repeat1,
  [968] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(285), 1,
      sym_word,
    STATE(12), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1010] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(287), 1,
      sym_word,
    STATE(11), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1052] = 10,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACEb,
    ACTIONS(17), 1,
      anon_sym_LBRACEi,
    ACTIONS(19), 1,
      anon_sym_LBRACEe,
    ACTIONS(25), 1,
      anon_sym_LBRACEul,
    ACTIONS(27), 1,
      anon_sym_LBRACEol,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_LBRACEm,
    ACTIONS(291), 1,
      sym_word,
    STATE(5), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1094] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(293), 1,
      sym_word,
    STATE(19), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1136] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(295), 1,
      sym_word,
    STATE(17), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1178] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(297), 1,
      sym_word,
    STATE(16), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1220] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(299), 1,
      sym_word,
    STATE(21), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1262] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(301), 1,
      sym_word,
    STATE(23), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1304] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(303), 1,
      sym_word,
    STATE(13), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1346] = 10,
    ACTIONS(181), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(187), 1,
      anon_sym_LBRACEb,
    ACTIONS(189), 1,
      anon_sym_LBRACEi,
    ACTIONS(191), 1,
      anon_sym_LBRACEe,
    ACTIONS(193), 1,
      anon_sym_LBRACEul,
    ACTIONS(195), 1,
      anon_sym_LBRACEol,
    ACTIONS(197), 1,
      anon_sym_LBRACEm,
    ACTIONS(305), 1,
      sym_word,
    STATE(18), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1388] = 10,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_LBRACEb,
    ACTIONS(17), 1,
      anon_sym_LBRACEi,
    ACTIONS(19), 1,
      anon_sym_LBRACEe,
    ACTIONS(25), 1,
      anon_sym_LBRACEul,
    ACTIONS(27), 1,
      anon_sym_LBRACEol,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_LBRACEm,
    ACTIONS(307), 1,
      sym_word,
    STATE(6), 12,
      sym_inline_code,
      sym_bold,
      sym_italic,
      sym_emph,
      sym_ref,
      sym_ref_with_text,
      sym_link,
      sym_tagged_ul,
      sym_tagged_ol,
      sym_math_inline,
      sym__inline,
      aux_sym_paragraph_repeat1,
  [1430] = 2,
    ACTIONS(311), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(309), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1451] = 2,
    ACTIONS(315), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(313), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1472] = 2,
    ACTIONS(319), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(317), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1493] = 2,
    ACTIONS(323), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(321), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1514] = 2,
    ACTIONS(327), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(325), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1535] = 2,
    ACTIONS(331), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(329), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1556] = 2,
    ACTIONS(335), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(333), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1577] = 2,
    ACTIONS(339), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(337), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1598] = 2,
    ACTIONS(343), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(341), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1619] = 2,
    ACTIONS(347), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(345), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1640] = 2,
    ACTIONS(351), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(349), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1661] = 2,
    ACTIONS(355), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(353), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1682] = 2,
    ACTIONS(359), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(357), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1703] = 2,
    ACTIONS(363), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(361), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1724] = 2,
    ACTIONS(367), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(365), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1745] = 2,
    ACTIONS(371), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(369), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1766] = 2,
    ACTIONS(375), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(373), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1787] = 2,
    ACTIONS(379), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACEm,
      sym_word,
    ACTIONS(377), 13,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_LBRACE_LBRACK,
      anon_sym_LBRACEv,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      sym_ul_bullet,
      sym_ol_number,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEmath,
  [1808] = 2,
    ACTIONS(331), 1,
      anon_sym_LBRACE,
    ACTIONS(329), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1824] = 2,
    ACTIONS(343), 1,
      anon_sym_LBRACE,
    ACTIONS(341), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1840] = 2,
    ACTIONS(323), 1,
      anon_sym_LBRACE,
    ACTIONS(321), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1856] = 2,
    ACTIONS(319), 1,
      anon_sym_LBRACE,
    ACTIONS(317), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1872] = 2,
    ACTIONS(339), 1,
      anon_sym_LBRACE,
    ACTIONS(337), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1888] = 2,
    ACTIONS(351), 1,
      anon_sym_LBRACE,
    ACTIONS(349), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1904] = 2,
    ACTIONS(315), 1,
      anon_sym_LBRACE,
    ACTIONS(313), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1920] = 2,
    ACTIONS(375), 1,
      anon_sym_LBRACE,
    ACTIONS(373), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1936] = 2,
    ACTIONS(371), 1,
      anon_sym_LBRACE,
    ACTIONS(369), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1952] = 2,
    ACTIONS(367), 1,
      anon_sym_LBRACE,
    ACTIONS(365), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1968] = 2,
    ACTIONS(363), 1,
      anon_sym_LBRACE,
    ACTIONS(361), 10,
      sym__newline,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LBRACEb,
      anon_sym_LBRACEi,
      anon_sym_LBRACEe,
      anon_sym_LBRACEul,
      anon_sym_LBRACEol,
      anon_sym_LBRACEm,
      sym_word,
  [1984] = 3,
    ACTIONS(381), 1,
      anon_sym_RBRACE,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    STATE(68), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [1995] = 3,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(385), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2006] = 3,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(387), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2017] = 3,
    ACTIONS(389), 1,
      anon_sym_RBRACE,
    ACTIONS(391), 1,
      anon_sym_LBRACE_DASH,
    STATE(68), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2028] = 3,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    ACTIONS(394), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2039] = 2,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    STATE(67), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2047] = 2,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    STATE(65), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2055] = 3,
    ACTIONS(396), 1,
      anon_sym_LBRACE,
    ACTIONS(398), 1,
      sym_heading_level,
    ACTIONS(400), 1,
      anon_sym_BANG,
  [2065] = 2,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    STATE(69), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2073] = 2,
    ACTIONS(383), 1,
      anon_sym_LBRACE_DASH,
    STATE(66), 2,
      sym_list_item,
      aux_sym_tagged_ul_repeat1,
  [2081] = 2,
    ACTIONS(402), 1,
      anon_sym_v_RBRACE,
    ACTIONS(404), 1,
      sym_verbatim_content,
  [2088] = 2,
    ACTIONS(406), 1,
      aux_sym_ref_id_token1,
    STATE(104), 1,
      sym_link_url,
  [2095] = 2,
    ACTIONS(408), 1,
      anon_sym_RBRACK_RBRACE,
    ACTIONS(410), 1,
      sym_code_content,
  [2102] = 2,
    ACTIONS(412), 1,
      anon_sym_BANG,
    ACTIONS(414), 1,
      anon_sym_COLON,
  [2109] = 2,
    ACTIONS(396), 1,
      anon_sym_LBRACE,
    ACTIONS(400), 1,
      anon_sym_BANG,
  [2116] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(92), 1,
      sym_ref_id,
  [2123] = 1,
    ACTIONS(418), 2,
      anon_sym_RBRACE,
      anon_sym_LBRACE_DASH,
  [2128] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(102), 1,
      sym_ref_id,
  [2135] = 2,
    ACTIONS(420), 1,
      anon_sym_RBRACK,
    ACTIONS(422), 1,
      sym_inline_code_content,
  [2142] = 2,
    ACTIONS(424), 1,
      anon_sym_RBRACK,
    ACTIONS(426), 1,
      sym_inline_code_content,
  [2149] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(105), 1,
      sym_ref_id,
  [2156] = 2,
    ACTIONS(416), 1,
      aux_sym_ref_id_token1,
    STATE(98), 1,
      sym_ref_id,
  [2163] = 2,
    ACTIONS(428), 1,
      anon_sym_BANG,
    ACTIONS(430), 1,
      anon_sym_COLON,
  [2170] = 2,
    ACTIONS(406), 1,
      aux_sym_ref_id_token1,
    STATE(106), 1,
      sym_link_url,
  [2177] = 2,
    ACTIONS(432), 1,
      anon_sym_LBRACE,
    ACTIONS(434), 1,
      anon_sym_BANG,
  [2184] = 2,
    ACTIONS(436), 1,
      anon_sym_RBRACE,
    ACTIONS(438), 1,
      sym_math_content,
  [2191] = 1,
    ACTIONS(440), 1,
      anon_sym_RBRACE,
  [2195] = 1,
    ACTIONS(442), 1,
      anon_sym_RBRACE,
  [2199] = 1,
    ACTIONS(444), 1,
      sym_math_content,
  [2203] = 1,
    ACTIONS(446), 1,
      ts_builtin_sym_end,
  [2207] = 1,
    ACTIONS(448), 1,
      anon_sym_RBRACE,
  [2211] = 1,
    ACTIONS(450), 1,
      anon_sym_RBRACE,
  [2215] = 1,
    ACTIONS(452), 1,
      anon_sym_RBRACK,
  [2219] = 1,
    ACTIONS(454), 1,
      anon_sym_RBRACE,
  [2223] = 1,
    ACTIONS(456), 1,
      anon_sym_RBRACE,
  [2227] = 1,
    ACTIONS(458), 1,
      sym_math_content,
  [2231] = 1,
    ACTIONS(460), 1,
      anon_sym_RBRACK_RBRACE,
  [2235] = 1,
    ACTIONS(462), 1,
      anon_sym_RBRACE,
  [2239] = 1,
    ACTIONS(464), 1,
      anon_sym_RBRACE,
  [2243] = 1,
    ACTIONS(466), 1,
      anon_sym_RBRACE,
  [2247] = 1,
    ACTIONS(468), 1,
      anon_sym_RBRACE,
  [2251] = 1,
    ACTIONS(470), 1,
      anon_sym_RBRACE,
  [2255] = 1,
    ACTIONS(472), 1,
      anon_sym_RBRACE,
  [2259] = 1,
    ACTIONS(474), 1,
      anon_sym_v_RBRACE,
  [2263] = 1,
    ACTIONS(476), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 153,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 250,
  [SMALL_STATE(10)] = 296,
  [SMALL_STATE(11)] = 342,
  [SMALL_STATE(12)] = 387,
  [SMALL_STATE(13)] = 432,
  [SMALL_STATE(14)] = 477,
  [SMALL_STATE(15)] = 522,
  [SMALL_STATE(16)] = 565,
  [SMALL_STATE(17)] = 610,
  [SMALL_STATE(18)] = 655,
  [SMALL_STATE(19)] = 700,
  [SMALL_STATE(20)] = 745,
  [SMALL_STATE(21)] = 790,
  [SMALL_STATE(22)] = 835,
  [SMALL_STATE(23)] = 880,
  [SMALL_STATE(24)] = 925,
  [SMALL_STATE(25)] = 968,
  [SMALL_STATE(26)] = 1010,
  [SMALL_STATE(27)] = 1052,
  [SMALL_STATE(28)] = 1094,
  [SMALL_STATE(29)] = 1136,
  [SMALL_STATE(30)] = 1178,
  [SMALL_STATE(31)] = 1220,
  [SMALL_STATE(32)] = 1262,
  [SMALL_STATE(33)] = 1304,
  [SMALL_STATE(34)] = 1346,
  [SMALL_STATE(35)] = 1388,
  [SMALL_STATE(36)] = 1430,
  [SMALL_STATE(37)] = 1451,
  [SMALL_STATE(38)] = 1472,
  [SMALL_STATE(39)] = 1493,
  [SMALL_STATE(40)] = 1514,
  [SMALL_STATE(41)] = 1535,
  [SMALL_STATE(42)] = 1556,
  [SMALL_STATE(43)] = 1577,
  [SMALL_STATE(44)] = 1598,
  [SMALL_STATE(45)] = 1619,
  [SMALL_STATE(46)] = 1640,
  [SMALL_STATE(47)] = 1661,
  [SMALL_STATE(48)] = 1682,
  [SMALL_STATE(49)] = 1703,
  [SMALL_STATE(50)] = 1724,
  [SMALL_STATE(51)] = 1745,
  [SMALL_STATE(52)] = 1766,
  [SMALL_STATE(53)] = 1787,
  [SMALL_STATE(54)] = 1808,
  [SMALL_STATE(55)] = 1824,
  [SMALL_STATE(56)] = 1840,
  [SMALL_STATE(57)] = 1856,
  [SMALL_STATE(58)] = 1872,
  [SMALL_STATE(59)] = 1888,
  [SMALL_STATE(60)] = 1904,
  [SMALL_STATE(61)] = 1920,
  [SMALL_STATE(62)] = 1936,
  [SMALL_STATE(63)] = 1952,
  [SMALL_STATE(64)] = 1968,
  [SMALL_STATE(65)] = 1984,
  [SMALL_STATE(66)] = 1995,
  [SMALL_STATE(67)] = 2006,
  [SMALL_STATE(68)] = 2017,
  [SMALL_STATE(69)] = 2028,
  [SMALL_STATE(70)] = 2039,
  [SMALL_STATE(71)] = 2047,
  [SMALL_STATE(72)] = 2055,
  [SMALL_STATE(73)] = 2065,
  [SMALL_STATE(74)] = 2073,
  [SMALL_STATE(75)] = 2081,
  [SMALL_STATE(76)] = 2088,
  [SMALL_STATE(77)] = 2095,
  [SMALL_STATE(78)] = 2102,
  [SMALL_STATE(79)] = 2109,
  [SMALL_STATE(80)] = 2116,
  [SMALL_STATE(81)] = 2123,
  [SMALL_STATE(82)] = 2128,
  [SMALL_STATE(83)] = 2135,
  [SMALL_STATE(84)] = 2142,
  [SMALL_STATE(85)] = 2149,
  [SMALL_STATE(86)] = 2156,
  [SMALL_STATE(87)] = 2163,
  [SMALL_STATE(88)] = 2170,
  [SMALL_STATE(89)] = 2177,
  [SMALL_STATE(90)] = 2184,
  [SMALL_STATE(91)] = 2191,
  [SMALL_STATE(92)] = 2195,
  [SMALL_STATE(93)] = 2199,
  [SMALL_STATE(94)] = 2203,
  [SMALL_STATE(95)] = 2207,
  [SMALL_STATE(96)] = 2211,
  [SMALL_STATE(97)] = 2215,
  [SMALL_STATE(98)] = 2219,
  [SMALL_STATE(99)] = 2223,
  [SMALL_STATE(100)] = 2227,
  [SMALL_STATE(101)] = 2231,
  [SMALL_STATE(102)] = 2235,
  [SMALL_STATE(103)] = 2239,
  [SMALL_STATE(104)] = 2243,
  [SMALL_STATE(105)] = 2247,
  [SMALL_STATE(106)] = 2251,
  [SMALL_STATE(107)] = 2255,
  [SMALL_STATE(108)] = 2259,
  [SMALL_STATE(109)] = 2263,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(72),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(77),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(75),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(83),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(25),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(31),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(32),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(35),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(27),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(71),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(70),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(90),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(93),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(7),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(79),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(83),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(25),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(31),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(32),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(71),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(70),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(93),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ol_item, 2),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ol_item, 2), SHIFT(79),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(83),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(25),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(31),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(32),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(71),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ol_item, 2), SHIFT(70),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ol_item, 2), SHIFT(93),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ol_item, 2), SHIFT(4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ul_item, 2),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ul_item, 2), SHIFT(79),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(83),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(25),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(31),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(32),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(71),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ul_item, 2), SHIFT(70),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ul_item, 2), SHIFT(93),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_ul_item, 2), SHIFT(4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(9),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(89),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(84),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(28),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(34),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(29),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(73),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(74),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2), SHIFT_REPEAT(100),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_content, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(89),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(84),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(28),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(34),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(29),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(73),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(74),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(100),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2), SHIFT_REPEAT(22),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_block, 2),
  [311] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_block, 2),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_ul, 3),
  [315] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tagged_ul, 3),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_with_text, 7, .production_id = 4),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_with_text, 7, .production_id = 4),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 7, .production_id = 5),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 7, .production_id = 5),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 2),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 2),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 4, .production_id = 3),
  [331] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 4, .production_id = 3),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, .production_id = 2),
  [335] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4, .production_id = 2),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_inline, 3, .production_id = 1),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_inline, 3, .production_id = 1),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_code, 2),
  [343] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_code, 2),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_block, 3, .production_id = 1),
  [347] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_block, 3, .production_id = 1),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tagged_ol, 3),
  [351] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tagged_ol, 3),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, .production_id = 1),
  [355] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, .production_id = 1),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_block, 3, .production_id = 1),
  [359] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_block, 3, .production_id = 1),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_code, 3),
  [363] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_code, 3),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, .production_id = 1),
  [367] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, .production_id = 1),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, .production_id = 1),
  [371] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, .production_id = 1),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emph, 3, .production_id = 1),
  [375] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emph, 3, .production_id = 1),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_block, 2),
  [379] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_block, 2),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tagged_ul_repeat1, 2),
  [391] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tagged_ul_repeat1, 2), SHIFT_REPEAT(33),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [402] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [408] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [418] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_item, 3),
  [420] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [424] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [436] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [438] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [440] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [442] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [444] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [446] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [448] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [450] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [452] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [454] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [456] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_id, 1),
  [458] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [460] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [462] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [464] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_url, 1),
  [466] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [468] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [470] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [472] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [474] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [476] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_odoc_mld(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
